
version: 2

models:
  - name: PROCUREMENT
    description: "A starter dbt model"
    depends_on:
      - source: RAW_DATA.CONFIRMATIONS

  - name: DTC
    description: "A starter dbt model"
    depends_on:
      - source: RAW_DATA.DTC

  - name: SALES
    description: "A starter dbt model"
    depends_on:
      - source: RAW_DATA.VEH MAPING LIST

  - name: DOCUMENTATION
    description: "A starter dbt model"
    depends_on:
      - source: RAW_DATA.DOCUMENTATION

  - name: LOGISTICS
    description: "A starter dbt model"
    depends_on:
      - source: RAW_DATA.LOGISTICS
  
