
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    depends_on:
      - source: AIRBYTE_SCHEMA.CONFIRMATIONS

# models:
#   - name: My_second_dbt
#     description: "A starter dbt model"
#     depends_on:
#       - source: AIRBYTE_SCHEMA.CONFIRMATIONS

  # - name: my_second_dbt_model
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       tests:
  #         - unique
  #         - not_null
